### ISSUE TITLE
packer-plugin-vagrant has been updated with breaking changes

### ISSUE THREAD

**Issue by dafyddj** [ppggff/vagrant-qemu#52] opened 2023-10-12 14:42 UTC
Hi,

`packer-plugin-vagrant` has recently been updated to v1.1.0 and the structure of the files included in the Vagrant box has changed. See https://github.com/hashicorp/packer-plugin-vagrant/pull/48

If I'm not mistaken, this causes the check on this line to fail: https://github.com/ppggff/vagrant-qemu/blob/4d85f60032bf0a4ef3f7d26f4a102fce1f3213f2/lib/vagrant-qemu/action/import.rb#L22

This is using `vagrant-qemu` version v0.3.5

**Comment by ppggff** [comment] 2023-10-13 01:37
Thanks, do you have a example box for test?

**Comment by dafyddj** [comment] 2023-10-13 11:19
You can try [this](https://www.dropbox.com/scl/fi/qjx28yk3ibpcnh6w2i226/alpine318-packer_plugin_v1.1.0.box?rlkey=m1fnci8ln0n7bvmik1qvjsqgm&dl=1) one

**Comment by ppggff** [comment] 2023-10-19 08:21
To support the new version of libvirt box, I need to find a workable libvirt machine for test.
(See how libvirt convert multiple disk config to qemu command)
It'll take a while.

There is temporary workaround for single disk box: use the image file directly.

Install box and find image path:

```
# install box as "test_new_box"
vagrant box add --name test_new_box ./alpine318-packer_plugin_v1.1.0.box

# find the image file, the default location for "test_new_box":
~/.vagrant.d/boxes/test_new_box/0/libvirt/box_0.img
```

Set `image_path` config in Vagrantfile. 
```
qe.image_path = "/Users/xxx/.vagrant.d/boxes/test_new_box/0/libvirt/box_0.img"
```

**Comment by dafyddj** [comment] 2023-10-19 14:01
Thanks for the update

**Comment by Xantios** [comment] 2024-01-20 14:38
running into this same issue, currently hardcoding paths in my Vagrantfile.
is there any plans on fixing this so i don't need a workaround ?

**Comment by unixerius** [comment] 2024-02-02 11:55
I've made a pull request to at least get this plugin working again with boxes that have one single drive image.

**Comment by ppggff** [comment] 2024-02-27 10:50
Please try the new v0.3.6

**Comment by unixerius** [comment] 2024-03-11 20:46
I can confirm that your version 0.3.6 seems to be working for me.

Please feel free to close this issue.

**Closed** 2024-03-12 04:12 UTC
